# Definition der Sensoren

# Example configuration entry
dallas:
  - id: dallasWaterSensor
    pin: D0

# Individual sensors
sensor:
  - platform: dallas
    id: waterSensor
    index: 0
    name: "Wassertemperatur"
