substitutions:
  platform: esp32

packages:
  device_base: !include aquamat-base.yaml

esphome:
  comment: $upper_devicename for $platform (mit sdd1306 Display)

esp32:
  board: esp32dev

###########################################################
# IO Controler
#
# I2C Definitionen
<<: !include io/i2c/esp32-i2c.yaml
# SPI Definitionen
<<: !include io/spi/esp32-spi.yaml
#
###########################################################

###########################################################
# Display Definitionen
#
# Font Definitionen
<<: !include utils/fonts.yaml
#

# Display Driver
<<: !include displays/esp32.yaml
#
###########################################################

###########################################################
# Pin Belegung
#
# Input Definitionen
<<: !include io/inputs/esp32-inputs.yaml
#
# Output Definitionen
#<<: !include io/esp32-outputs.yaml
<<: !include io/outputs/esp32-outputs.yaml
#
# LEDs
#<<: !include io/esp32-lights.yaml
<<: !include aktoren/esp32-lights.yaml
#
###########################################################

###########################################################
# Individuelle Hardware
#
# Sensoren

<<: !include aktoren/esp32-sensors.yaml
#
###########################################################

# Automatitionen
<<: !include utils/esp32-interval.yaml
