substitutions:
  devicename: aquamat
  upper_devicename: AquaMat
  platform: esp8266

packages:
  # Wifi Definition
  wifi: !include wifi/wifi.yaml
  # OTA Definition
  ota: !include ota/ota.yaml
  # MQTT Definition
#  mqtt: !include mqtt/mqtt.yaml

esphome:
  # Custom Code
  includes:
    - lib

  comment: $upper_devicename for $platform
  name: $devicename
  name_add_mac_suffix: true

  project:
    name: "aqua.mat"
    version: "1.0.0"

  on_boot:
    priority: -100
    then:
      - logger.log: "AquaMat gebootet"

logger:

# Enable Home Assistant API
api:
  password: "0f56927cab6822b10952ae56aa1a1530"

#demo:

#############################################################
# Globale Variablen
# und andere Definitionen
#
#globals:

# Farben
<<: !include utils/colors.yaml
#
#############################################################


# Timer Events
<<: !include utils/time.yaml

# Pumpen Definition
<<: !include aktoren/pumps.yaml

# Buttons
<<: !include aktoren/buttons.yaml
