substitutions:
  platform: esp8266

packages:
  device_base: !include aquamat-base.yaml

esphome:
  comment: $upper_devicename for $platform (mit sdd1306 Display)

esp8266:
  board: nodemcuv2

###########################################################
# IO Controler
#
# I2C Definitionen
#<<: !include io/DevKitC-i2c.yaml
# SPI Definitionen
<<: !include io/i2c/esp8266-i2c.yaml
#<<: !include io/spi/esp8266-spi.yaml
#
###########################################################

###########################################################
# Display Definitionen
#
# Font Definitionen
<<: !include utils/fonts.yaml
#
# Display Driver
<<: !include displays/sdd1306.yaml
#<<: !include displays/esp8266-st7735.yaml
#<<: !include displays/ili9341.yaml
#
###########################################################

###########################################################
# Pin Belegung
#
# Input Definitionen
<<: !include io/inputs/esp8266-inputs.yaml

# Output Definitionen
<<: !include io/outputs/esp8266-outputs.yaml

# LEDs
<<: !include aktoren/esp8266-lights.yaml
#
###########################################################

###########################################################
# Individuelle Hardware
#
# Sensoren

<<: !include aktoren/sensors.yaml
#
###########################################################

# Automatitionen
<<: !include utils/interval.yaml
