substitutions:
  devicename: aquamat
  upper_devicename: AquaMat
  platform: esp8266

packages:
  # Wifi Definition
  wifi: !include wifi/wifi.yaml
  # OTA Definition
#  ota: !include ota/ota.yaml
  # MQTT Definition
#  mqtt: !include mqtt/mqtt.yaml

esphome:
  libraries:
#    - greiman/SSD1306Ascii

  comment: $upper_devicename for $platform
  name: $devicename
  name_add_mac_suffix: true

  project:
    name: "aqua.mat"
    version: "1.0.0"

  on_boot:
    priority: -100
    then:
      - logger.log: "AquaMat gebootet"

logger:

# Enable Home Assistant API
api:
  password: "0f56927cab6822b10952ae56aa1a1530"

#demo:

#############################################################
# Globale Variablen
# und andere Definitionen
#
globals:
  - id: mytemperature
    type: int
    restore_value: yes
  - id: mytime
    type: ESPTime
    restore_value: no
    # Standrad Font Größe (für Zeilenberechungen)
  - id: systemFontSize
    type: int
    restore_value: no
    initial_value: '16'

# Farben
<<: !include utils/colors.yaml
#
#############################################################


# Timer Events
<<: !include utils/time.yaml

# Automatitionen
<<: !include utils/interval.yaml

# Pumpen Definition
<<: !include aktoren/pumps.yaml

# Sensoren
<<: !include aktoren/sensors.yaml

# Buttons
<<: !include aktoren/buttons.yaml
