substitutions:
  platform: esp32

packages:
  device_base: !include aquamat-base.yaml

esphome:
  comment: $upper_devicename for $platform

  on_boot:
    priority: -100
    then:
      - logger.log: "AquaMat gebootet"
      - logger.log: "Pumpen abschalten"
      - fan.turn_on:
          id: pump_1
          direction: FORWARD
          speed: 1
      - fan.turn_off: pump_1
      - fan.turn_on:
          id: pump_2
          direction: FORWARD
          speed: 2
      - fan.turn_off: pump_2
      - fan.turn_on:
          id: pump_1
          direction: FORWARD
          speed: 1
      - fan.turn_off: pump_3
#      - lambda: id(pump_1).turn_off().set_speed(0).set_direction(fan::FanDirection::FORWARD).perform();
#      - lambda: id(pump_2).turn_off().set_speed(0).set_direction(fan::FanDirection::FORWARD).perform();
#      - lambda: id(pump_3).turn_off().set_speed(0).set_direction(fan::FanDirection::FORWARD).perform();

esp32:
  board: esp32dev

###########################################################
# IO Controler
#
# I2C Definitionen
<<: !include io/i2c/esp32-i2c.yaml
# SPI Definitionen
#<<: !include io/spi/esp32-spi.yaml
#
###########################################################

###########################################################
# Display Definitionen
#
# Font Definitionen
<<: !include utils/fonts.yaml
#

# Display Driver
<<: !include displays/esp32.yaml
#
###########################################################

###########################################################
# Pin Belegung
#
# Input Definitionen
<<: !include io/inputs/esp32-inputs.yaml
#
# Output Definitionen
#<<: !include io/esp32-outputs.yaml
<<: !include io/outputs/esp32-outputs.yaml
#
# LEDs
#<<: !include io/esp32-lights.yaml
#<<: !include aktoren/esp32-lights.yaml
#
###########################################################

###########################################################
# Individuelle Hardware
#
# Sensoren

<<: !include aktoren/esp32-sensors.yaml
#
###########################################################

# Automatitionen
<<: !include utils/esp32-interval.yaml
