substitutions:
  platform: esp32

packages:
  device_base: !include aquamat-base.yaml

esphome:
  comment: $upper_devicename for $platform (mit sdd1306 Display)

esp32:
  board: az-delivery-devkit-v4

###########################################################
# IO Controler
#
# I2C Definitionen
<<: !include io/i2c/DevKitC-i2c.yaml
# SPI Definitionen
<<: !include io/spi/DevKitC-spi.yaml
#
###########################################################

###########################################################
# Display Definitionen
#
# Font Definitionen
<<: !include utils/fonts.yaml
#

# Display Driver
<<: !include displays/DevKitC.yaml
#
###########################################################

###########################################################
# Pin Belegung
#
# Input Definitionen
<<: !include io/inputs/esp32-inputs.yaml
#
# Output Definitionen
#<<: !include io/esp32-outputs.yaml
<<: !include io/outputs/DevKitC-outputs.yaml
#
# LEDs
#<<: !include io/esp32-lights.yaml
<<: !include aktoren/DevKitC-lights.yaml
#
###########################################################

###########################################################
# Individuelle Hardware
#
# Sensoren

<<: !include aktoren/DevKitC-sensors.yaml
#
###########################################################

# Automatitionen
<<: !include utils/DevKitC-interval.yaml
