#############################################################
# ILI9341 Display (TFT)
# See: https://esphome.io/components/display/ili9341.html
#############################################################

- platform: ili9341
  model: TFT 1.8
  id: mediumTFT
  cs_pin: SS
  dc_pin: SCK
#    led_pin: 32  # see note below ###
#    reset_pin: 33

  lambda: |-
    it.fill(COLOR_WHITE);
    it.print(0, 0, id(my_font), id(my_red), TextAlign::TOP_LEFT, "Hello World!");
    it.rectangle(0,  it.get_height() / 2, it.get_width(), it.get_height(), id(my_red));
