binary_sensor:
  # Gelber Buttons
  - platform: gpio
    name: Gelber Button
    id: yellowButton
    pin:
      number: D7
      mode:
        input: true
        pullup: true
    on_release:
      then:
        - logger.log: Gelber Button Signal
        - fan.toggle: pump_1

  # Blauer Buttons
  - platform: gpio
    name: Blauer Button
    id: blueButton
    pin:
      number: D8
      mode:
        input: true
        pullup: true
    on_release:
      then:
        - logger.log: Blauer Button Signal
        - fan.toggle: pump_2

  # Roter Buttons
  - platform: gpio
    name: Roter Button
    id: redButton
    pin:
      number: D9
      mode:
        input: true
        pullup: true
    on_release:
      then:
        - logger.log: Roter Button Signal
        - fan.toggle: pump_3
