packages:
  device_base: !include aquamat-base.yaml

esphome:
  comment: $upper_devicename for $platform (mit sdd1306 Display)

esp8266:
  board: nodemcuv2

#esp32:
#  board: esp32dev

# Display Definition
#<<: !include displays/sdd1306.yaml

# Input Definitionen
<<: !include io/esp8226-inputs.yaml

# Output Definitionen
<<: !include io/esp8226-outputs.yaml
